name: BSD CI

on: [push, pull_request]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  SPEC_SPLIT_DOTS: 160
  TZ: America/New_York

jobs:
  freebsd-14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: vmactions/freebsd-vm@f0552d3b69211736abd97f02ff3d4674c56b73b1 # v1.5.5
        with:
          mem: 8192
          release: "14"
          envs: 'SPEC_SPLIT_DOTS TZ'
          prepare: |
            pkg install -y crystal git gmake libxml2 openssl pcre2 pkgconf
          run: |
            gmake std_spec
