name: macOS CI

on: [push, pull_request]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  RELEASE: "1.17.1"
  REVISION: "1"
  SPEC_SPLIT_DOTS: 160
  CRYSTAL_OPTS: -Dwithout_iconv

jobs:
  darwin-test:
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.arch }}
    strategy:
      matrix:
        include:
        - runs-on: macos-13
          arch: x86_64-darwin
        - runs-on: macos-14
          arch: aarch64-darwin
        - runs-on: macos-15
          arch: aarch64-darwin
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          limit-access-to-actor: true

      - name: Setup
        run: |
          brew install bdw-gc libffi llvm
          curl -sL "https://github.com/crystal-lang/crystal/releases/download/$RELEASE/crystal-$RELEASE-$REVISION-darwin-universal.tar.gz" | tar zx
          echo "PATH=$PWD/crystal-$RELEASE-$REVISION/bin:$(brew --prefix)/opt/llvm/bin:$PATH" >> $GITHUB_ENV

      - name: Test
        run: ./bin/simple_ci

